#!/usr/bin/env python3
"""Generate the LVGL RGB565 image assets for the badge application.

Reproducible pipeline: source artwork lives outside the repository in the
developer's working folder; this script reads it, produces trimmed / quantized
RGB565 C arrays under ``assets/images/``, and writes layout previews to a
temporary directory for review.

Usage:
    python3 tools/make_badge_assets.py --source-dir <folder with raw artwork> \
        --smt-logo <SMT logo png>
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "assets" / "images"

# Dedication-page background blur, in source pixels. Baked in at generation time:
# the panel is 240x320 on an ESP32-C3 with no PSRAM, so a runtime blur would need a
# snapshot plus a second full-screen buffer. Baking costs nothing extra in flash --
# the RGB565 payload is the same size either way. Radius 2 softens the supplied
# 2px line work into a haze while keeping the weave readable; 3 or more erases it
# and the page collapses into flat navy.
BG_BLUR_RADIUS = 2.0

# ---------------------------------------------------------------------------
# Brand palette, sampled from the WorldSkills Shanghai 2026 brand package.
# ---------------------------------------------------------------------------
WHITE = (255, 255, 255)
INK = (0x00, 0x22, 0x3A)
RED = (0xEB, 0x00, 0x2A)
ORANGE = (0xEE, 0x75, 0x22)
YELLOW = (0xFF, 0xB8, 0x1B)
BLUE = (0x05, 0x63, 0xA1)
MAROON = (0x68, 0x16, 0x28)
TEAL = (0x3D, 0xB6, 0xB6)
CYAN = (0x28, 0xCA, 0xD3)
GOLD = (0xD4, 0xC2, 0x42)
# SMT brand blue, sampled from the supplied "2020简版logo-原色.png".
SMT_BLUE = (0x00, 0x96, 0xE0)

SILVER_1 = (0xFF, 0xFF, 0xFF)
SILVER_2 = (0xE4, 0xEA, 0xF0)
SILVER_3 = (0xC2, 0xCD, 0xD8)
SILVER_4 = (0x98, 0xA6, 0xB5)
SILVER_5 = (0x6E, 0x7E, 0x90)
SILVER_6 = (0x4A, 0x5A, 0x6B)

# The mortise-and-tenon emblem is built from exactly these six colours.
# Cyan and gold are deliberately excluded: area averaging blends neighbours into
# off-palette pixels, and snapping those to cyan/gold adds a false fringe.
EMBLEM_PALETTE = (WHITE, RED, ORANGE, YELLOW, BLUE, INK, MAROON)

# The SMT lockup is a single flat blue on transparency.
SMT_PALETTE = (WHITE, SMT_BLUE)


def nearest(pixel: tuple[int, int, int], palette) -> tuple[int, int, int]:
    r, g, b = pixel
    return min(palette, key=lambda c: (c[0] - r) ** 2 + (c[1] - g) ** 2 + (c[2] - b) ** 2)


def trim_on_white(im: Image.Image, tolerance: int = 12) -> Image.Image:
    rgb = im.convert("RGB")
    mask = Image.new("L", rgb.size, 0)
    px = rgb.load()
    mpx = mask.load()
    w, h = rgb.size
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if not (r > 255 - tolerance and g > 255 - tolerance and b > 255 - tolerance):
                mpx[x, y] = 255
    box = mask.getbbox()
    return rgb.crop(box) if box else rgb


def trim_on_alpha(im: Image.Image, threshold: int = 24) -> Image.Image:
    """Crop transparent-background artwork to its visible pixels."""
    rgba = im.convert("RGBA")
    mask = rgba.getchannel("A").point(lambda v: 255 if v > threshold else 0)
    box = mask.getbbox()
    return rgba.crop(box) if box else rgba


def flatten_on_white(im: Image.Image) -> Image.Image:
    """Composite transparency onto white: LVGL RGB565 carries no alpha channel."""
    rgba = im.convert("RGBA")
    return Image.alpha_composite(Image.new("RGBA", rgba.size, WHITE + (255,)), rgba).convert("RGB")


def clamp565(im: Image.Image) -> Image.Image:
    """Clamp to the RGB565 grid so the asset matches what the panel can show."""
    px = im.load()
    for y in range(im.size[1]):
        for x in range(im.size[0]):
            r, g, b = px[x, y]
            px[x, y] = ((r >> 3) << 3 | (r >> 5),
                        (g >> 2) << 2 | (g >> 6),
                        (b >> 3) << 3 | (b >> 5))
    return im


def postprocess(im: Image.Image, size: tuple[int, int], palette=None) -> Image.Image:
    resample = Image.Resampling.BOX if palette is not None else Image.Resampling.LANCZOS
    im = im.convert("RGB").resize(size, resample)
    if palette is not None:
        px = im.load()
        for y in range(size[1]):
            for x in range(size[0]):
                px[x, y] = nearest(px[x, y], palette)
    return clamp565(im)


def to_rgb565(im: Image.Image) -> list[int]:
    out = []
    for r, g, b in im.convert("RGB").getdata():
        out.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
    return out


def emit_c(name: str, symbol: str, im: Image.Image, comment: str) -> None:
    w, h = im.size
    values = to_rgb565(im)
    lines = [
        "// Generated by tools/make_badge_assets.py -- do not edit by hand.",
        f"// {comment}",
        f"// Source size: {w}x{h} RGB565 (little-endian uint16_t).",
        "",
        '#include "lvgl.h"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        f"static const LV_ATTRIBUTE_MEM_ALIGN uint16_t {symbol}_map[] = {{",
    ]
    for i in range(0, len(values), 12):
        chunk = ", ".join(f"0x{v:04X}" for v in values[i:i + 12])
        lines.append(f"    {chunk},")
    lines += [
        "};",
        "",
        f"const lv_image_dsc_t {symbol} = {{",
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
        "    .header.cf = LV_COLOR_FORMAT_RGB565,",
        f"    .header.w = {w},",
        f"    .header.h = {h},",
        f"    .header.stride = {w * 2},",
        f"    .data_size = sizeof({symbol}_map),",
        f"    .data = (const uint8_t *){symbol}_map,",
        "};",
        "",
    ]
    (OUT_DIR / f"{name}.c").write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote assets/images/{name}.c  ({w}x{h}, {w * h * 2} bytes)")


def emit_a8(name: str, symbol: str, alpha: Image.Image, comment: str) -> None:
    """Emit an alpha-only (A8) asset.

    LVGL paints an A8 image with the widget's ``image_recolor`` colour and uses
    this plane purely as a mask, so a single-colour lockup needs no RGB data at
    all: one byte per pixel, and the source antialiasing survives. Use it when
    the artwork must sit on a non-white background, where an RGB565 copy would
    have to carry an opaque plate colour of its own.
    """
    w, h = alpha.size
    values = list(alpha.convert("L").getdata())
    lines = [
        "// Generated by tools/make_badge_assets.py -- do not edit by hand.",
        f"// {comment}",
        f"// Source size: {w}x{h} A8 (one byte per pixel, alpha only).",
        "",
        '#include "lvgl.h"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {symbol}_map[] = {{",
    ]
    for i in range(0, len(values), 16):
        chunk = ", ".join(f"0x{v:02X}" for v in values[i:i + 16])
        lines.append(f"    {chunk},")
    lines += [
        "};",
        "",
        f"const lv_image_dsc_t {symbol} = {{",
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
        "    .header.cf = LV_COLOR_FORMAT_A8,",
        f"    .header.w = {w},",
        f"    .header.h = {h},",
        f"    .header.stride = {w},",
        f"    .data_size = sizeof({symbol}_map),",
        f"    .data = (const uint8_t *){symbol}_map,",
        "};",
        "",
    ]
    (OUT_DIR / f"{name}.c").write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote assets/images/{name}.c  ({w}x{h} A8, {w * h} bytes)")


# ---------------------------------------------------------------------------
# Pixel-art medal, drawn on a 30x30 logical grid then blown up 4x.
# ---------------------------------------------------------------------------
def _star_vertices(cx, cy, r_out, r_in, points=5, rotation=-90.0):
    import math
    verts = []
    for i in range(points * 2):
        radius = r_out if i % 2 == 0 else r_in
        angle = math.radians(rotation + i * 180.0 / points)
        verts.append((cx + radius * math.cos(angle), cy + radius * math.sin(angle)))
    return verts


def draw_medal() -> Image.Image:
    """Silver medal on a 30x30 logical grid, expanded 4x into 120x120.

    Shapes are drawn on a 4x supersampled canvas and reduced with area
    averaging, so the pixel-art result keeps clean silhouettes instead of the
    ragged edges a direct nearest-neighbour draw would produce.
    """
    grid, ss = 30, 4
    n = grid * ss
    cx, cy = 14.5, 19.0
    r_out, r_bevel, r_inner = 9.0, 7.5, 6.6

    def mask_layer(draw_fn):
        layer = Image.new("L", (n, n), 0)
        draw_fn(ImageDraw.Draw(layer))
        return layer.resize((grid, grid), Image.Resampling.BOX).load()

    disc = mask_layer(lambda d: d.ellipse(
        [(cx - r_out) * ss, (cy - r_out) * ss, (cx + r_out) * ss, (cy + r_out) * ss], fill=255))
    inner = mask_layer(lambda d: d.ellipse(
        [(cx - r_inner) * ss, (cy - r_inner) * ss, (cx + r_inner) * ss, (cy + r_inner) * ss], fill=255))
    bevel = mask_layer(lambda d: d.ellipse(
        [(cx - r_bevel) * ss, (cy - r_bevel) * ss, (cx + r_bevel) * ss, (cy + r_bevel) * ss], fill=255))
    star = mask_layer(lambda d: d.polygon(
        [(x * ss, y * ss) for x, y in _star_vertices(cx, cy, 4.9, 2.1)], fill=255))

    strap = Image.new("L", (n, n), 0)
    sd = ImageDraw.Draw(strap)
    for mirror in (False, True):
        quad = [(6.0, -0.5), (9.6, -0.5), (16.4, 10.5), (13.2, 10.5)]
        if mirror:
            quad = [(29.0 - x, y) for x, y in quad]
        sd.polygon([(x * ss, y * ss) for x, y in quad], fill=255)
    strap_px = strap.resize((grid, grid), Image.Resampling.BOX).load()

    im = Image.new("RGB", (grid, grid), WHITE)
    for y in range(grid):
        for x in range(grid):
            if strap_px[x, y] > 140 and disc[x, y] <= 140 and y <= 11:
                # Navy edging stripe along the inside of each ribbon strap.
                t = (x - cx)
                im.putpixel((x, y), INK if abs(t) < 1.6 else RED)
            if disc[x, y] <= 140:
                continue
            dx, dy = x - cx, y - cy
            diag = dx + dy
            if star[x, y] > 140:
                im.putpixel((x, y), SILVER_1)
            elif inner[x, y] <= 140:
                im.putpixel((x, y), SILVER_4 if diag > 3.0 else SILVER_3)
            elif bevel[x, y] <= 140:
                light = diag < -2.0 and ((x * 5 + y * 3) % 7) < 4
                im.putpixel((x, y), SILVER_1 if light else SILVER_3)
            else:
                # Rim, lit from the upper left with a single specular notch.
                specular = dx < -2.0 and dy < 1.0 and dx + dy < -3.0
                im.putpixel((x, y), SILVER_1 if specular else SILVER_5)

    # Ordered dithering on the disc face gives the flat fill a brushed-metal read.
    for y in range(grid):
        for x in range(grid):
            if disc[x, y] <= 140 or star[x, y] > 140:
                continue
            diagonal = (x - cx) + (y - cy)
            if bevel[x, y] <= 140:
                continue
            if ((x * 3 + y * 5) % 5) == 0:
                base = im.getpixel((x, y))
                im.putpixel((x, y), SILVER_2 if base == SILVER_3 else SILVER_3)
            elif diagonal > 4.5 and ((x + y) % 3) == 0:
                im.putpixel((x, y), SILVER_4)

    return im.resize((grid * ss, grid * ss), Image.Resampling.NEAREST)


def build(source_dir: Path, preview_dir: Path, smt_logo: Path) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    preview_dir.mkdir(parents=True, exist_ok=True)

    logo = trim_on_white(Image.open(source_dir / "shanghai2026 logo.png"))
    lw, lh = logo.size
    emit_c("wss_logo_red", "wss_logo_red",
           postprocess(logo, (round(56 * lw / lh), 56)),
           "WorldSkills Shanghai 2026 lockup, red on white, trimmed.")
    emit_c("wss_logo_red_lg", "wss_logo_red_lg",
           postprocess(logo, (round(64 * lw / lh), 64)),
           "WorldSkills Shanghai 2026 lockup, larger variant.")
    postprocess(logo, (round(64 * lw / lh), 64)).save(preview_dir / "logo_red.png")

    emblem = trim_on_white(Image.open(source_dir / "Rule" / "榫卯.png"))
    emblem_small = postprocess(emblem, (30, 30), EMBLEM_PALETTE)
    emblem_small.resize((120, 120), Image.Resampling.NEAREST).save(preview_dir / "emblem_30.png")
    emit_c("emblem_pixel", "emblem_pixel",
           emblem_small.resize((120, 120), Image.Resampling.NEAREST),
           "Mortise-and-tenon emblem as 30x30 pixel art, expanded 4x.")

    medal = draw_medal()
    medal.save(preview_dir / "medal_120.png")
    emit_c("medal_silver", "medal_silver", medal,
           "Pixel-art silver medal, 30x30 logical grid expanded 4x.")

    # Placeholder portrait for the work-pass page. Supply your own square-ish
    # photo as ``portrait-source.jpeg`` in the source folder; it is personal data,
    # so the generated file is listed in .gitignore and never committed.
    portrait = Image.open(source_dir / "portrait-source.jpeg").convert("RGB")
    pw, ph = portrait.size
    side = min(pw, ph)
    portrait = portrait.crop(((pw - side) // 2, (ph - side) // 2,
                              (pw + side) // 2, (ph + side) // 2))
    portrait = postprocess(portrait, (84, 84))
    portrait.save(preview_dir / "portrait.png")
    emit_c("portrait_sample", "portrait_sample", portrait,
           "Sample portrait, centre square crop.")

    # SMT lockup for the "Presented by" row: 18 px tall, so width follows the
    # source aspect ratio. BOX averaging plus a two-colour snap keeps the
    # wordmark edges crisp instead of washing out into soft blue.
    smt = trim_on_alpha(Image.open(smt_logo))
    sw, sh = smt.size
    smt_size = (round(18 * sw / sh), 18)
    smt_small = postprocess(flatten_on_white(smt), smt_size, SMT_PALETTE)
    smt_small.resize((smt_size[0] * 8, smt_size[1] * 8), Image.Resampling.NEAREST).save(
        preview_dir / "smt_logo.png")
    emit_c("smt_logo", "smt_logo", smt_small,
           "SMT emblem and wordmark, flattened on white, snapped to the brand blue.")

    # Same lockup as an alpha plane for the dark dedication page: there the
    # artwork must not carry the white plate the RGB565 copy above needs.
    smt_alpha = smt.getchannel("A").resize(smt_size, Image.Resampling.BOX)
    smt_alpha.resize((smt_size[0] * 8, smt_size[1] * 8), Image.Resampling.NEAREST).save(
        preview_dir / "smt_logo_a8.png")
    emit_a8("smt_logo_a8", "smt_logo_a8", smt_alpha,
            "SMT emblem and wordmark as an alpha plane; recolour to the brand blue.")

    # Dedication-page background. The supplied artwork is a seamless geometric
    # pattern in landscape, so a native-resolution window the size of the panel
    # is cropped rather than scaled: nothing is lost because the pattern has no
    # focal content, and the thin line work keeps its real geometry.
    bg = Image.open(source_dir / "Rule" / "Backgroud page3.png").convert("RGB")
    bw, bh = bg.size
    bx, by = (bw - 240) // 2, (bh - 320) // 2
    # Crop first, then blur: blurring before the crop would pull in pixels from
    # outside the window and give the four edges a different character. Pillow
    # clamps edge pixels, so blurring after the crop cannot darken the border.
    bg_crop = bg.crop((bx, by, bx + 240, by + 320))
    bg_blur = bg_crop.filter(ImageFilter.GaussianBlur(BG_BLUR_RADIUS))
    bg_blur = clamp565(bg_blur)
    bg_blur.save(preview_dir / "bg_page3.png")
    emit_c("bg_page3", "bg_page3", bg_blur,
           "Dedication-page background: seamless navy pattern cropped 1:1 to the "
           f"panel, then Gaussian-blurred (radius {BG_BLUR_RADIUS:g}px) to push the "
           "line work behind the dedication text.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--smt-logo", type=Path, required=True,
                        help="SMT lockup PNG with a transparent background")
    parser.add_argument("--preview-dir", type=Path, default=Path("/tmp/badge-preview"))
    args = parser.parse_args()
    build(args.source_dir, args.preview_dir, args.smt_logo)
    print(f"Previews: {args.preview_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())